# Generated by Django 5.0.1 on 2024-02-18 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='date_paid',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 18, 22, 50, 33, 796216), null=True),
        ),
    ]
