# Generated by Django 5.0.1 on 2024-02-18 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_fee_date_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='date_paid',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
