# Generated by Django 5.0.1 on 2024-02-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_fee_date_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='date_paid',
            field=models.DateField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
    ]
