# Generated by Django 5.0.1 on 2024-02-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_fee_date_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='date_paid',
            field=models.DateField(default='2024-10-10'),
        ),
    ]
