# Generated by Django 5.0.1 on 2024-01-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(default='Boy', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='child',
            unique_together={('first_name', 'last_name', 'date_of_birth', 'emergency_contact_number')},
        ),
    ]
