# Generated by Django 5.0.1 on 2024-01-31 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ondate', models.DateField()),
                ('meal_description', models.TextField(blank=True, null=True)),
                ('nap_duration', models.DurationField(blank=True, null=True)),
                ('playtime_activities', models.TextField(blank=True, null=True)),
                ('bathroom_breaks', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('mood', models.CharField(blank=True, max_length=20, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('medication_given', models.TextField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.child')),
            ],
        ),
    ]
