# Generated by Django 5.0.1 on 2024-01-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_dailyactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivity',
            name='ondate',
            field=models.DateField(auto_now=True),
        ),
    ]
