# Generated by Django 5.0.1 on 2024-02-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_childmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmedia',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], max_length=10, null=True),
        ),
    ]
