# Generated by Django 5.0.1 on 2024-02-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_childmedia_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='childmedia',
            name='activity_type',
            field=models.CharField(choices=[('meal', 'Meal'), ('nap', 'Nap'), ('playtime', 'Playtime'), ('bathroom', 'Bathroom'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
