# Generated by Django 5.0.1 on 2024-02-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_childmedia_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='parent1_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='parent1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='parent2_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='parent2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
