# Generated by Django 5.0.1 on 2024-02-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_child_address_child_blood_group_child_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='unique_id',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
