# Generated by Django 5.0.1 on 2024-02-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_child_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='child_fees',
            field=models.FloatField(default=0),
        ),
    ]
