# Generated by Django 5.0.1 on 2024-02-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_child_child_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
