# Generated by Django 5.0.2 on 2024-03-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_dailyactivity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
