# Generated by Django 5.0.3 on 2024-03-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_dailyactivity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='childmedia',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
