# Generated by Django 5.0.3 on 2024-03-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_childmedia_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyactivity',
            name='image',
        ),
    ]
