# Generated by Django 5.0.3 on 2024-03-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_remove_dailyactivity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmedia',
            name='activity_type',
            field=models.CharField(choices=[('Meal', 'Meal'), ('Nap', 'Nap'), ('Playtime', 'Playtime'), ('Bathroom', 'Bathroom'), ('Other', 'Other')], default='other', max_length=20),
        ),
    ]
