# Generated by Django 5.0.3 on 2024-03-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_alter_childmedia_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmedia',
            name='media_type',
            field=models.CharField(blank=True, choices=[('Image', 'Image'), ('Video', 'Video')], max_length=10, null=True),
        ),
    ]
