# Generated by Django 5.0.3 on 2024-03-19 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_learningresource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningresource',
            name='uploaded_by',
        ),
    ]
