# Generated by Django 5.0.3 on 2024-03-21 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_remove_learningresource_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningresource',
            name='file',
        ),
        migrations.CreateModel(
            name='LearningResourceMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='learning_resources/')),
                ('lrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.learningresource')),
            ],
        ),
    ]
