# Generated by Django 5.0.3 on 2024-04-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_remove_learningresource_file_learningresourcemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
