# Generated by Django 5.0.7 on 2024-10-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_rooms_child_room'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='child',
            unique_together={('first_name', 'last_name', 'date_of_birth', 'parent1_contact_number')},
        ),
        migrations.AlterField(
            model_name='child',
            name='parent1_contact_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='child',
            name='parent1_name',
            field=models.CharField(default='1234567890', max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='child',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='child',
            name='emergency_contact_number',
        ),
    ]
