# Generated by Django 5.0.7 on 2024-10-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_alter_child_medical_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='unique_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
