# Generated by Django 5.0.7 on 2024-10-22 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_alter_child_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.rooms')),
            ],
        ),
    ]
