# Generated by Django 5.0.7 on 2024-10-22 14:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_roommedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommedia',
            name='media_file',
            field=models.FileField(default='', upload_to='room_media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roommedia',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roommedia',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='students.rooms'),
        ),
    ]
