# Generated by Django 5.0.1 on 2024-02-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(default='asdfg22342', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
