# Generated by Django 5.0.1 on 2024-02-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_customuser_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(default='Staff', max_length=20),
        ),
    ]
