# Generated by Django 5.0.2 on 2024-03-06 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0015_alter_dailyactivity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('relation_to_child', models.CharField(max_length=35)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('unique_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.child')),
            ],
        ),
        migrations.CreateModel(
            name='ChildcareAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(max_length=100)),
                ('scheduled_time', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, default=30, max_length=30)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parent.parentmodel')),
            ],
        ),
    ]
